ICL-5435 chore: nx react
Consdata/heimdall pull request #40
Opened 2022-02-17 08:47 UTC by martini449

2022-02-20 19:42 UTC, Chrrapek submitted a review, later dismissed
Yea, oramy

2022-02-24 09:38 UTC, dmejer commented
Czemu frontend/consdata? Nie moze odrazu byc pod frontend cała appka z nxem ? Po co nam ten pośredni katalog?

2022-02-24 09:38 UTC, dmejer commented
Gradle nie trigeruje builda nxa. Raczej chcemy po wpisaniu  ./gradlew build, by budowalo sie wsio.

2022-02-24 09:39 UTC, dmejer requested changes
trzeba zaktualizowac README.md, bo jest nieaktualne. Wywalić śmieci

2022-02-24 09:41 UTC, dmejer commented
Czemu nie wywalisz backendu ? Potrzebujemy tylko jakis scanner, ktory bedzie zawieral skrypcik

2022-06-09 08:03 UTC, Chrrapek approved these changes

2022-06-09 08:04 UTC, drolewski approved these changes

2022-06-09 08:20 UTC, dmejer approved these changes

2022-06-09 08:57 UTC, merged